version: '3.8'

services:
  email-verifier:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - ENABLE_SMTP_CHECK=true
    volumes:
      # Mount templates and static files for development
      - ./templates:/root/templates
      - ./static:/root/static
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl:ro
    depends_on:
      - email-verifier
    restart: unless-stopped
    profiles:
      - production

networks:
  default:
    name: email-verifier-network
