services:
  email-verifier:
    container_name: email-verifier
    build: .
    ports:
      - "8081:8081"
    volumes:
      - ./templates:/app/templates
      - ./static:/app/static
    restart: unless-stopped
